# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-thakir_prayer_times

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Provides Prayer times for Sailfish OS
Version:    4.0.31
Release:    1
Group:      Qt/Qt
License:    GPLv3
URL:        https://sites.google.com/site/thakirprayertimes/thakir-prayer-times-en
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-thakir_prayer_times.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   qt5-qtdeclarative-import-xmllistmodel
Requires:   nemo-qml-plugin-contextkit-qt5
BuildRequires:  pkgconfig(sailfishapp) >= 0.0.10
BuildRequires:  pkgconfig(Qt5Multimedia)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(keepalive)
BuildRequires:  desktop-file-utils

%description
Thakir Prayer Times provides Prayer times for Sailfish OS.

# This description section includes metadata for SailfishOS:Chum, see
# https://github.com/sailfishos-chum/main/blob/main/Metadata.md
%if 0%{?_chum}
PackageName: Thakir Prayer Times
Type: desktop-application
DeveloperName: HAFIANE Mohamed
Categories:
 - Utility
Custom:
  Repo: https://github.com/hafmed/harbour-thakir_prayer_times
Icon: https://github.com/hafmed/harbour-thakir_prayer_times/blob/master/icon-thakir_sailfish_Quran_new.svg
Screenshots:
 - https://github.com/hafmed/harbour-thakir_prayer_times/blob/master/screenshots/Screenshot1.png
 - https://github.com/hafmed/harbour-thakir_prayer_times/blob/master/screenshots/Screenshot2.png
 - https://github.com/hafmed/harbour-thakir_prayer_times/blob/master/screenshots/Screenshot3.png
Url:
  Homepage: https://github.com/hafmed/harbour-thakir_prayer_times
  #Help: https://github.com/piggz/harbour-advanced-camera/discussions
  Bugtracker: https://github.com/hafmed/harbour-thakir_prayer_times/issues
  #Donation: https://www.paypal.me/piggz
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5  \
    VERSION=%{version}

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor
%{_datadir}/%{name}/translations
%{_datadir}/%{name}/qml
%{_datadir}/%{name}/sounds
%{_bindir}/%{name}
# >> files
# << files

 %changelog
* Sat Apr 1 2023 HAFIANE MOHAMED <thakir.dz@gmail.com> 4.0.31-1
- Minor SFOS 4.5 fixes
- Added Chum metadata

* Tue Mar 29 2022 HAFIANE MOHAMED <thakir.dz@gmail.com> 4.0.21-1
- Some bugs fixed
- Add Sensors permission for compass
- Compatibility to Sailfish X 4.4.0.58 EA

* Thu Mar 17 2022 HAFIANE MOHAMED <thakir.dz@gmail.com> 4.0.9-1
- Add Quran
- Sailjail support
- Compatibility to Sailfish X 4.3.0.15

* Thu Dec 9 2021 HAFIANE MOHAMED <thakir.dz@gmail.com> 3.1.9-1
- Some bugs fixed

* Sun Dec 5 2021 HAFIANE MOHAMED <thakir.dz@gmail.com> 3.1.7-1
- Compatibility to Sailfish X 4.3.0.12

* Mon Nov 15 2021 HAFIANE MOHAMED <thakir.dz@gmail.com> 3.1.5-1
- Add "Application permissions"

* Tue Apr 13 2021 HAFIANE MOHAMED <thakir.dz@gmail.com> 3.1.0-1
- Add support for My Backup
- Release aarch64 build

* Tue Apr 13 2021 HAFIANE MOHAMED <thakir.dz@gmail.com> 3.0.10-1
- Compatibility to Sailfish X 4.0.1.48

* Fri Jun 5 2020 HAFIANE MOHAMED <thakir.dz@gmail.com> 3.0.9-1
- Compatibility to Sailfish X 3.3.0.16

* Tue Sep 17 2019 HAFIANE MOHAMED <thakir.dz@gmail.com> 3.0.7-1
- Update to Nemo.KeepAlive 1.2

* Thu May 23 2019 HAFIANE MOHAMED <thakir.dz@gmail.com> 3.0.5-1
- Some bugs fixed

* Sat Dec 15 2018 HAFIANE MOHAMED <thakir.dz@gmail.com> 3.0.1-5
- Some bugs fixed

* Wed Dec 5 2018 HAFIANE MOHAMED <thakir.dz@gmail.com> 3.0.0-1
- Add ability to listening to some Athkar

* Thu Nov 29 2018 HAFIANE MOHAMED <thakir.dz@gmail.com> 2.7.5-1
- Some bugs fixed

* Mon Nov 26 2018 HAFIANE MOHAMED <thakir.dz@gmail.com> 2.7.1-1
- Add ability listining to morning and evening Athkar

* Sun Nov 25 2018 HAFIANE MOHAMED <thakir.dz@gmail.com> 2.5.7-5
- Add ability to change the profile of the mobile to Silent during Jommaa prayer

* Thu Nov 15 2018 HAFIANE MOHAMED <thakir.dz@gmail.com> 2.5.1-5
- Compatibility to Sailfish X 3
- Some bugs fixed
- Enable/Disable Stop Athan by Turning the phone upside down

* Thu Jun 9 2016 HAFIANE MOHAMED <thakir.dz@gmail.com> 2.5.0-1
- Some bugs fixed
- Add Arabic translation (With or without Arabic number)
- Add Turkish translation (Thanks to Dr_Electronic)
- Add ability to change the profile of the mobile to Silent during Taraweeh prayer in Ramadan
- Add Hikmato Al-Youm (Arabic)

* Thu May 5 2016 HAFIANE MOHAMED <thakir.dz@gmail.com> 2.0.7-1
- Some bugs fixed

* Sun May 1 2016 HAFIANE MOHAMED <thakir.dz@gmail.com> 2.0.5-1
- Add TURKEY_DIYANET method

* Fri Apr 29 2016 HAFIANE MOHAMED <thakir.dz@gmail.com> 2.0.1-1
- Some bugs fixed

* Tue Apr 19 2016 HAFIANE MOHAMED <thakir.dz@gmail.com> 2.0.0-1
- Enable/Disable Alert before Adhan
- Enable/Disable Silent mode after Adhan (during Prayer)

* Sat Apr 9 2016 HAFIANE MOHAMED <thakir.dz@gmail.com> 1.9.7-1
- Enable/Disable Adhan in Silent mode
- Control Volume Adhan
- Enable/Disable Adhan from cover

* Fri Apr 1 2016 HAFIANE MOHAMED <thakir.dz@gmail.com> 1.9.5-1
- GPS bugs fixed

* Tue Jan 12 2016 HAFIANE MOHAMED <thakir.dz@gmail.com> 1.9.1-7
- Some bugs fixed
- Add Islamic/Hijri Important Events

* Sat Dec 5 2015 HAFIANE MOHAMED <thakir.dz@gmail.com> 1.9.0-1
- Add ability to save any configuration in a favorite

* Sun Nov 29 2015 HAFIANE MOHAMED <thakir.dz@gmail.com> 1.7.0-1
- Add direction of Quibla

* Sat Nov 28 2015 HAFIANE MOHAMED <thakir.dz@gmail.com> 1.5.0-15
- Add am/pm

* Sun Nov 1 2015 HAFIANE MOHAMED <thakir.dz@gmail.com> 1.5.0-1
- Add Adhan (Click on remaining time button to stop Adhan).
- Add GPS.
- Add French translation.

* Thu Oct 29 2015 HAFIANE MOHAMED <thakir.dz@gmail.com> 1.0.0-1
- Initial release.
